[package]
name = "ptyme"
version = "0.1.0"
authors = ["Derek Parker <parkerderek86@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17.0"
mio = { version = "0.7.0", features = ["os-poll", "os-util"] }
